# Generated by Django 2.2.2 on 2020-04-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_diagnoised', models.BooleanField(default=False)),
                ('uploaded_by_doc', models.CharField(default='', max_length=20)),
                ('downloaded_by_rad', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
