# Generated by Django 2.2.2 on 2020-04-10 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200411_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
