# Generated by Django 2.2.2 on 2020-04-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_uploadeddoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddoc',
            name='doc',
            field=models.FileField(upload_to=''),
        ),
    ]
