# Generated by Django 2.2.2 on 2020-04-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200411_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddoc',
            name='doc',
            field=models.FileField(upload_to='media/'),
        ),
    ]
